### ISSUE TITLE
What is the next step

### ISSUE THREAD

**Issue by faressoft** [jochen-schweizer/express-prom-bundle#14]
What is the next step to visualize these data with Graphana ?

**Comment by disjunction** [comment]
The next step is to set up prometheus and point it to your service:
https://prometheus.io/docs/prometheus/latest/getting_started/

You'll be able to see the metrics in prometheus itself

After you make sure the metrics are properly read by prometheus you can connect Grafana to prometheus. That's it
https://prometheus.io/docs/visualization/grafana/

**Comment by disjunction** [comment]
@mikepuglisi I don't have any predefined dashboards, but I can share a couple of queries I use:

1. **request count per 5m**. Shows a chart per http method and path. Here I use `sum` because I have multiple instances of the same app, and `increase` shows the request in given time range instead of just continuously growing chart

- Query: `sum(increase(http_request_duration_seconds_count[5m])) by (method, path)`
- Legend format: `{{ method }} {{ path }}`

2. **Errors chart**. Shows a chart per HTTP error code, displaying all 5xx and only 400 error. (I ignore other 40x errors, as those are often generated by bots and alike).

- Query: `sum(increase(http_request_duration_seconds_count{app="$app",status_code=~"5.*|400"}[1h])) by (status_code)`
- Legend format: `{{ status_code }}`

Hope it helps!

**Comment by poteirard** [comment]
It would be very beneficial for the users of this libraries to have a [Grafana dashboard](https://grafana.com/dashboards) just like other libs like [swagger-stats](https://github.com/slanatech/swagger-stats). I would love to help on this but unfortunately I'm new with this...

**Comment by marwenbk** [comment]
did anyone make a Dashboard?
