### ISSUE TITLE
prom-client 11.2.0 breaks middleware

### ISSUE THREAD

**Issue by peterkuiper** [jochen-schweizer/express-prom-bundle#22]
When running the latest version of `prom-client` these metrics disappear:

```
# HELP up 1 = up, 0 = not up
# TYPE up gauge
up 1

# HELP http_request_duration_seconds duration histogram of http responses labeled with: status_code, method, path
# TYPE http_request_duration_seconds histogram
```

I haven't had the time to figure out what is new in `prom-client`. I have set the version to `11.1.3` as a quick fix.

**Comment by disjunction** [comment]
hm, that's unfortunate. Minor versions should normally be backwards-compatible, and this lib is quite straight-forward in what it does. Thanks for reporting it!

**Comment by disjunction** [comment]
I couldn't reproduce this problem. It works fine for me.

I suspect there is a misunderstanding. Bare in mind: **express-prom-bundle** has a direct dependency on **prom-client**. When you were testing it it was `~11.1.2`, thus you COULD NOT use `11.2.0` at all unless you meddled with the library. Since today release I upgraded the dependency to `~11.2.1`

If you have `prom-client@11.2.0` installed in your app separately, then in your app you actually have 2 different **prom-client instances**, one which came with **express-prom-bundle**, and another - your own. They don't share the metrics, so it might be you were collecting the data with one client, while trying to read from another one.

Until now you could use a workaround: instead of installing and requiring `prom-client`, you could directly access the one, coming with **express-prom-bundle** as follows:

```js
const promClient = require('express-prom-bundle').promClient
```

With the new release 5.x prom-client will become a peer dependency and you won't have this problem again.

Please reopen if my guess is wrong and you still experience the problem, in which case I'd need some reproducible test case.
