### ISSUE TITLE
Question/Feature Request: Filter out status codes

### ISSUE THREAD

**Issue by RangarajKaushikSundar** [jochen-schweizer/express-prom-bundle#28]
Is there a way I can completely filter out certain status codes? The `formatStatusCode` function gives us the option to combine status codes, but not ignore them.

**Comment by disjunction** [comment]
There is no way, and I agree it would be nice to have it.

As a workaround you can transform the `status_code` to say "ignored". And then delete or change the other labels so that all those are collapsed into just one line in metrics. It shouldn't have any impact  on the traffic or performance this way.

**Comment by RangarajKaushikSundar** [comment]
Good idea. You can close this issue OR keep it open as a feature request.  😄

**Comment by RangarajKaushikSundar** [comment]
BTW. Thanks for the quick response @disjunction 👍

**Comment by SyedAsadAbrar** [comment]
@disjunction Could you share an example for this?
