### ISSUE TITLE
Adding native prom-client metrics seems to be overridden

### ISSUE THREAD

**Issue by Kostending** [jochen-schweizer/express-prom-bundle#29]
I need to add some custom metrics but it seems to fail/be overridden.

Fx. running the "advanced example", where the native prom-client metric "c1" is added will not show anything in the metrics.

**Comment by disjunction** [comment]
I just checked it once again. It worked as expected.

The most common problem is that for some reason prom-clinet module you use when defining the metric is different from prom-client used in this lib. And they do not see each-other.

You can ensure it's the same module by using the following:
```js
const bundle = require('express-prom-bundle');
const promClient = bundle.promClient;
// register your metrics in promClient
```
... instead of relying on peer dependency:
```js
const bundle = require('express-prom-bundle');
const promClient = require('prom-client'); 
```
Hope it helps!

**Comment by Kostending** [comment]
That helps! Thanks a bunch!
