### ISSUE TITLE
updating dependencies

### ISSUE THREAD

**Issue by jybleau** [jochen-schweizer/express-prom-bundle#3]
Hello,

Is there a blocking reason why dependencies, like ```prom-client```, are outdated? (current version is 6, package version is 3)

If no, would you like a pull request on that matter?

Thanks

**Comment by disjunction** [comment]
Hi,
thanks for pointing it out!

The new version of prom-bundle partially overlaps with the functionality of express-prom-bundle, namely by providing default metrics and an internal metrics registry. That's why it's not just version bumping in package.json.

Thanks for offering help, but I'll make an upgrade soon myself.

**Comment by disjunction** [comment]
Upgrade done in 08d98b4, already published on npm

For compatibility reasons the default metrics introduced in prom-client will NOT be provided automatically. If you still want them, use **keepDefaultMetrics** option
