### ISSUE TITLE
prom-client out of date

### ISSUE THREAD

**Issue by Industrial** [jochen-schweizer/express-prom-bundle#7]
Hi.

I want to send custom metrics using expressPromBundle.promClient.Gauge for example.

The API has changed, and now works differently. between the latest stable and 6.3.0

**Comment by disjunction** [comment]
Hi,
that's true. The prom-client was in such an active development that i preferred to stay back for a while. But it looks like it's time for an update. The new major version is coming soon.

Thanks for bringing this up.

**Comment by disjunction** [comment]
I've just published v3.0.0. It should be backwards-compatible, unless the consumer was abusing some undocumented features.

FYI: in future i consider releasing 4.0.0 version (not-backwards compatible), with the following main changes:
- cleaner options, especially regarding overlap between includePath and normalizePath
- prom-client will become a peer dependency, so that everyone can upgrade it independent of this lib

Cheers

**Comment by Industrial** [comment]
Cool, thanks :-)
